export const PROMPTS = [
    "The best way to scare a burglar is...",
    "A terrible name for a pet goldfish.",
    "What really killed the dinosaurs.",
    "The worst thing to say at a funeral.",
    "Something you shouldn't say to your doctor.",
    "A rejected flavor of ice cream.",
    "The unsexiest feature a person can have.",
    "What the Queen really keeps in her purse.",
    "The worst thing to find in your burrito.",
    "A bad substitute for a toothbrush.",
    "What dogs think about when they bark.",
    "The weirdest thing to find in your browser history.",
    "A rejected superhero name.",
    "The worst place to propose.",
    "What aliens really want from Earth.",
    "A terrible slogan for a dating app.",
    "The worst thing to say to a cop.",
    "A bad reason to break up with someone.",
    "What you shouldn't put on a resume.",
    "The worst thing to whisper in someone's ear.",
    "A rejected Disney movie title.",
    "The worst thing to bring to a potluck.",
    "What you shouldn't say on a first date.",
    "A terrible name for a rock band.",
    "The worst thing to do in an elevator.",
    "What cats are really plotting.",
    "The worst thing to say during sex.",
    "A bad name for a strip club.",
    "The worst thing to find under your bed.",
    "What you shouldn't say to your boss.",
    "A terrible name for a perfume.",
    "The worst thing to do at a wedding.",
    "What you shouldn't say to a flight attendant.",
    "A bad name for a law firm.",
    "The worst thing to say to a teacher.",
    "What you shouldn't say to a judge.",
    "A terrible name for a hospital.",
    "The worst thing to do in a library.",
    "What you shouldn't say to a mechanic.",
    "A bad name for a airline.",
    "The worst thing to say to a dentist.",
    "What you shouldn't say to a bartender.",
    "A terrible name for a gym.",
    "The worst thing to do in a movie theater.",
    "What you shouldn't say to a waiter.",
    "A bad name for a hotel.",
    "The best pickup line for a ghost.",
    "Something you'd find in a magician's pockets.",
    "The worst way to describe the taste of water.",
    "A secret talent of the President.",
    "If animals could talk, which one would be the rudest?",
    "The most useless superpower.",
    "A rejected title for a self-help book.",
    "What you shouldn't say to a mime.",
    "The worst thing to put on a pizza.",
    "A bad name for a boat.",
    "The worst thing to say to a tax collector.",
    "What you shouldn't say to a librarian.",
    "A terrible name for a university.",
    "The worst thing to do in a museum.",
    "What you shouldn't say to a zookeeper."
];

export const BOT_WORDS = ["Potato", "Sledgehammer", "Glitter", "Taxes", "Spaghetti", "Nuke", "Unicorn", "Moist", "Crusty", "Bazinga"];
